// playground/web-vue/src/app/app-root.vue
<script setup lang="ts">
import { computed, onMounted, ref } from "vue";
import { createGreeting, fetchHealth, listCapabilities, type HealthResponse } from "@uniframe/core";

const greeting = createGreeting("Vue Web");
const health = ref<HealthResponse>({ ok: false, service: "api" });
const capabilities = computed(() => listCapabilities());

onMounted(async () => {
  health.value = await fetchHealth();
});
</script>

<template>
  <main class="shell">
    <section class="hero">
      <p class="eyebrow">Vue hedefi</p>
      <h1>{{ greeting.title }}</h1>
      <p>{{ greeting.message }}</p>
      <span :class="health.ok ? 'status good' : 'status'">
        {{ health.ok ? "API bagli" : "API bekleniyor" }}
      </span>
    </section>

    <section class="grid">
      <article v-for="item in capabilities" :key="item">
        <span />
        <h2>{{ item }}</h2>
        <p>Bu yetenek Vue hedefinde de ayni core library uzerinden gelir.</p>
      </article>
    </section>
  </main>
</template>

// playground/web-react/src/app/app-root.tsx
import { useEffect, useState } from "react";
import { createGreeting, createStorage, fetchHealth, listCapabilities } from "@uniframe/core";
import "../style.css";

const storage = createStorage("react");

export function AppRoot() {
  const [health, setHealth] = useState({ ok: false, service: "api" });
  const [count, setCount] = useState(() => storage.get("count", 0));
  const greeting = createGreeting("React Web");

  useEffect(() => {
    fetchHealth().then(setHealth);
  }, []);

  function increment() {
    setCount((current) => storage.set("count", current + 1));
  }

  return (
    <main className="shell">
      <section className="hero">
        <p className="eyebrow">React hedefi</p>
        <h1>{greeting.title}</h1>
        <p>{greeting.message}</p>
        <div className="actions">
          <button onClick={increment}>Sayac {count}</button>
          <span className={health.ok ? "status good" : "status"}>
            {health.ok ? "API bagli" : "API bekleniyor"}
          </span>
        </div>
      </section>

      <section className="grid">
        {listCapabilities().map((item) => (
          <article key={item}>
            <span />
            <h2>{item}</h2>
            <p>Bu yetenek ortak proje modelinin bir parcasi olarak calisir.</p>
          </article>
        ))}
      </section>
    </main>
  );
}
