// playground/desktop/renderer/src/app/app-root.vue
<script setup lang="ts">
import { createGreeting, listCapabilities } from "@uniframe/core";

const greeting = createGreeting("Desktop Renderer");
const capabilities = listCapabilities().slice(0, 6);
</script>

<template>
  <main class="desktop-shell">
    <section class="workspace">
      <p class="eyebrow">Desktop UI</p>
      <h1>{{ greeting.title }}</h1>
      <p>{{ greeting.message }}</p>
    </section>

    <section class="panel-grid">
      <article v-for="item in capabilities" :key="item">
        <strong>{{ item }}</strong>
        <span>Desktop renderer icinden calisiyor.</span>
      </article>
    </section>
  </main>
</template>

// apps/mobile-react/src/app/app-root.tsx
import { useEffect, useState } from "react";
import { createGreeting, fetchHealth, listCapabilities } from "@uniframe/core";
import "../style.css";

export function AppRoot() {
  const [health, setHealth] = useState({ ok: false });
  const greeting = createGreeting("Mobile");

  useEffect(() => {
    fetchHealth().then(setHealth);
  }, []);

  return (
    <main className="phone">
      <header>
        <p>Mobile hedefi</p>
        <h1>{greeting.title}</h1>
      </header>
      <section className="panel">
        <p>{greeting.message}</p>
        <strong>{health.ok ? "API bagli" : "API bekleniyor"}</strong>
      </section>
      <nav>
        {listCapabilities()
          .slice(0, 4)
          .map((item) => (
            <button key={item}>{item}</button>
          ))}
      </nav>
    </main>
  );
}
